---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-runtime-agentic-layer-ai-v1alpha1-agent
  failurePolicy: Fail
  name: magent-v1alpha1.kb.io
  rules:
  - apiGroups:
    - runtime.agentic-layer.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agents
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-runtime-agentic-layer-ai-v1alpha1-agent
  failurePolicy: Fail
  name: vagent-v1alpha1.kb.io
  rules:
  - apiGroups:
    - runtime.agentic-layer.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agents
  sideEffects: None
