apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: AgentGateway
metadata:
  labels:
    app.kubernetes.io/name: agent-runtime-operator
    app.kubernetes.io/managed-by: kustomize
  name: agent-gateway
spec:
  # The class name of which implementation to use.
  agentGatewayClassName: "krakend"

  # Number of gateway replicas
  replicas: 2

  # Request timeout
  timeout: "30s"
---
# Minimal AgentGateway configuration
apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: AgentGateway
metadata:
  labels:
    app.kubernetes.io/name: agent-runtime-operator
    app.kubernetes.io/managed-by: kustomize
  name: minimal-gateway
spec: