# Example ToolServer using stdio transport (sidecar mode)
# This creates a ToolServer resource that can be injected as a sidecar container into agent pods.
# No standalone deployment or service is created for stdio transport.
#
# Note: When injected as a sidecar, you would typically need to:
# - Mount volumes for database access (e.g., emptyDir or persistent volumes)
# - Configure the agent to communicate with this tool server via stdio
apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: ToolServer
metadata:
  labels:
    app.kubernetes.io/name: agent-runtime-operator
    app.kubernetes.io/managed-by: kustomize
  name: example-stdio-toolserver
spec:
  protocol: mcp
  transportType: stdio
  # Official MCP SQLite server from Docker Hub
  image: mcp/sqlite:latest
  # SQLite MCP server arguments
  args:
    - "--db-path"
    - "/mcp/test.db"
  env:
    - name: LOG_LEVEL
      value: info
